#!/bin/bash

export AWS_ACCESS_KEY_ID=$S3_KEY
export AWS_SECRET_ACCESS_KEY=$S3_SECRET

for i in {1..20}; do
    ( NAME=$S3_PATH/test-$i-`date +%s`.tar.gz && \
    echo 'test' | gof3r put -b $S3_BUCKET -k $NAME --endpoint $S3_ENDPOINT > /dev/null 2>&1 && \
    echo "upload $NAME" ) &
done

wait

go run purger.go 10
